# Listelerin Öğelerine Erişmek

In [ ]:
kardiz = "python"
kardiz[0]

In [1]:
liste= [[0,1,2],[3,4,5],[6,7,8]]
liste[0][1]

1

# Listelerin Öğelerini Değiştirmek

In [ ]:
kardiz = "istihza"
kardiz = "İ" + kardiz[1:]
kardiz

In [ ]:
renkler = ["kırmızı", "sarı", "mavi", "yeşil", "beyaz"]
print(renkler)

In [ ]:
renkler[0] = "siyah"
print(renkler)

# Listeye Öğe Eklemek

In [3]:
liste = [2, 4, 5, 7]

In [4]:
liste + [8]

[2, 4, 5, 7, 8]

# Listeleri Birleştirmek

In [5]:
derlenen_diller = ["C", "C++", "C#", "Java"]
yorumlanan_diller = ["Python", "Perl", "Ruby"]

In [ ]:
programlama_dilleri = derlenen_diller + yorumlanan_diller


In [6]:
#########################################################################

# Sözlükler

In [9]:
sözlük = {"kitap"      : "book",
          "bilgisayar" : "computer",
          "programlama": "programming",
          "dil"        : "language",
          "defter"     : "notebook"}

In [10]:
sözlük["kitap"]

'book'

**listelerde ki erişmeye çalışınca sözlükler hata veriyo**

In [11]:
sözlük[0]

KeyError: 0

## Sözlük öğelerine erişmek


Şu anda işlememiz gereken son ana veri tipimiz sözlüklerdir. Sözlükler şu ana kadar öğrendiğimiz veri tiplerinden farklı olarak "gruplara" sahip olmamızı sağlar, ancak indexe göre çalışmak yerine Key/Value (Anahtar/Değer) çiftlerini kullanılırlar. Bunun bazı önemli faydaları var, ancak öncesinde nasıl çalıştığını görelim.

Önemli Not: Sözlükler de küme parantezleriyle gösterilir, ancak bir set olarak algılanmamaları için Key ve Value değerlerinden oluşması gerekir.

In [1]:
new_dictionary = {'key_for_this_thing': 8}
print(new_dictionary['key_for_this_thing'])

8


Sözlükler, her bir key değerinin içerisinde birden fazla farklı veri tipi bulundurabilir.

In [2]:
new_dictionary = {'key_for_a_list': [0,1,2,3,4], 'key_for_another_dictionary': {'bob': 1}}
print(new_dictionary['key_for_a_list'])

[0, 1, 2, 3, 4]


In [3]:
print(new_dictionary['key_for_another_dictionary'])
print(new_dictionary['key_for_another_dictionary']['bob'])

{'bob': 1}
1


In [4]:

career_stats = {'babe_ruth': {1914: ["Red Sox", 5, 10, 0], 1915:['Red Sox', 43, 104, 4]},
                'gavvy_cravath': {1914: ['Phillies',149,604,14]}}

print(career_stats['babe_ruth'])
print(career_stats['babe_ruth'][1914])

{1914: ['Red Sox', 5, 10, 0], 1915: ['Red Sox', 43, 104, 4]}
['Red Sox', 5, 10, 0]


In [5]:
# Ek olarak sadece key ve value değerine de ulaşılabilir.
print(career_stats.keys())
print(career_stats.values())

dict_keys(['babe_ruth', 'gavvy_cravath'])
dict_values([{1914: ['Red Sox', 5, 10, 0], 1915: ['Red Sox', 43, 104, 4]}, {1914: ['Phillies', 149, 604, 14]}])


Sözlükleri sevmemizin nedeni, veri almada gerçekten hızlı olmaları ve içermek istediğimiz her değere bir anahtar atamamıza izin vermeleridir.

# Sözlüklere Öğe Eklemek

In [ ]:
özlük = {}

In [ ]:
sözlük[anahtar] = değer

In [ ]:
sözlük["Ahmet"] = "Adana"

In [ ]:
sözlük

# Sözlük Öğeleri Üzerinde Değişiklik Yapmak

In [ ]:
notlar = {'Seda': 98, 'Ege': 95, 'Mehmet': 77,
'Zeynep': 100, 'Deniz': 95, 'Ahmet': 45}

In [ ]:
notlar["Ahmet"] = 65
print(notlar)

In [ ]:
#######################################################

# Numpy

In [13]:
import numpy as np
# 2 boyutlu bir NumPy dizisi oluştur
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 2. satır, 3. sütundaki elemana eriş
print(my_2d_array[1, 2])


6


In [14]:
my_2d_array[0:2,1]

array([2, 5])

In [19]:
 my_2d_array[:1] # başlangıç 0.satırdan 1 e kadar

array([[1, 2, 3]])

In [ ]:
numpy da toplama

In [24]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

In [25]:
numpy_array_from_list+5

array([ 6,  7,  8,  9, 10])

In [27]:
numpy_array_from_list[0]+5

6